// Code generated by sqlc. DO NOT EDIT.

package repository

import ()

type ApplicantInfo struct {
	ApplicantID    int32
	ResumeLocation string
	CompanyName    string
}

type Employer struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
}

type Posting struct {
	ID                 int32
	Title              string
	CompanyName        string
	CompanyDescription string
	PostingDescription string
	Salary             int32
}

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
}
