// Code generated by sqlc. DO NOT EDIT.

package repository

import ()

type Posting struct {
	ID                 int32
	Title              string
	CompanyName        string
	CompanyDescription string
	PostingDescription string
	Salary             int32
}
